### ISSUE TITLE
mitivation of mpower-2

### ISSUE THREAD

**Issue by a1png** [Sage-Bionetworks/mPower-2-iOS#55]
Hi,
I am studying on mpower app codes and I am curious about the motivation of this new version of mpower.
Besides shifting from obj-c to swift, I do not find code for calculation of pd scores as in the original mpower codes. Is it still developing or migrated to server?

**Comment by Erin-Mounts** [comment]
Hi,

We're building an entirely new mPower 2.0 from the ground up based on lessons learned from the original study and from several other apps/studies we've done or been involved with since then. It will have different ways of assessing and looking at historical data and providing insights to the participant, and as you've surmised, those parts haven't been built yet.

**Comment by a1png** [comment]
thank you
